### ISSUE TITLE
Pages without translations in sitemap if L != 0

### ISSUE THREAD

**Issue by bernhardberger** [lochmueller/google_services#11]
If you have a sitemap for a language other than default there are broken links to pages which don't have a translation.

Pull Request coming shortly.

**Comment by lochmueller** [comment]
Solved by https://github.com/lochmueller/google_services/pull/13 I think.
Thanks....

**Comment by bernhardberger** [comment]
Missed something though as TYPO3 6.x does need the pages_language_overlay table for retrieving the localization..

Pull request follows shortly..
