### ISSUE TITLE
RealURL 2.x delivers pagetitles in default language instead of localized patch segments for L<>0 when not logged in in BE

### ISSUE THREAD

**Issue by bernhardberger** [lochmueller/google_services#15]
...with @dmitryd shutting me down in an almost moron like way, maybe you can shed some light onto this (https://github.com/dmitryd/typo3-realurl/issues/186)

It's reproducable for me across various TYPO3 7.6 installations with realurl 2.x and a real issue with the generated sitemap.xml as it generates invalid links...

I just stumbled across an issue with realurl 2.x (latest stable or dev, doesn't matter) delivering wrong page titles on localized records when not logged in in the backend.

I use EXT:google_services to create XML sitemaps of our websites.

Internally it uses:
$url = $obj->getUriBuilder() ->setTargetPageUid($uid) ->build();

to build the frontend urls for the pages.

Expected output for /fr/sitemap.xml would be forexample:

If I take the page "search" for example which is localized in french with the title "rechercher" I would expect the following output:
http://domain.tld/fr/rechercher/
but it delivers
http://domain.tld/fr/search/

instead. As you see it recognizes the L parameter and mapps it to "fr" but it doesn't get me the localized segment anymore...

Only when not logged in in backend. Disabling cache and clearing the install tool cache don't change anything.

My TypoScript setup regarding language:
`
config {
sys_language_uid = 0
language = en
locale_all = en_GB
htmlTag_langKey = en
sys_language_overlay = hideNonTranslated
sys_language_mode = strict
linkVars = L
}

[globalVar = GP:L = 1]
config.sys_language_uid = 1
config.language = fr
config.locale_all = fr_FR
config.htmlTag_langKey = fr
[global]
`

**Comment by bernhardberger** [comment]
...nevermind. Seems to be a bug within the realurl caches after further investigation. Maybe I go after it and try to fix it if I've calmed down a bit from his behaviour.. 

can be closed / deleted.

**Comment by lochmueller** [comment]
Thanks for the information. I also ran into this problem, but on the regular webpage and not in the sitemap.xml. If the bug is solved in realurl this would be great. I close this issue, because it is not related to the sitemap generation... Regards, Tim

**Comment by bernhardberger** [comment]
Sorry for reopening this, but could you maybe please report this bug in his GitHub repo?

After I reported it i got loterally thrown out of it.. sent me a lonk to the mailong list for my 'local problem' and after stating that it was reproducable he left me a link to 'Getting Help' and banned from the GitHub repo...

After investigating I actually found part of the problem and wanted to provide a pull request, but woth being blocked from the repo I can't even clone it anymore..

It's a bit ridiculous, but it seems you can't even talk to that guy, let alone try to help...

**Comment by lochmueller** [comment]
Do you try to contact Dmirty via Slack? I will check this issue in the next days and create a issue in the realurl issue tracker...
