### ISSUE TITLE
AbstractXmlView is breaking TYPO3 cache generation

### ISSUE THREAD

**Issue by pitchart** [lochmueller/google_services#18]
I encountered a bug using the sitemap plugin configured in typoscript with a specific page type for sitemap.xml.

The first rendering of the sitemap page is fine, but all others page calls leads to the "Page is being generated" message.
After a deep search in TYPO3's frontend rendering classes, it appears that the AbstractXmlView::render() function is responsible for this problem :
* Pages or other records are requested and stored to the cache
* AbstractXmlView returns the content with a `die` so the rest of the 'afterRequestDispatch' signal is not triggered.

Due to this last point, the cache generation for the page is considered as not finished.

Using the extension nc_staticfilecache, it appears that the static cache is also not generated.

I've fixed the problem locally by overriding the Index and Overview views to bypass their parent's rendering, and adding the Content-type header in the typoscript setup of the sitemap page.

Here is the typoscript configuration :

```
[userFunc = TYPO3\CMS\Core\Utility\ExtensionManagementUtility::isLoaded('google_services')]
lib.googleservice_sitemap = USER
lib.googleservice_sitemap {
       userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
       vendorName = FRUIT
       extensionName = GoogleServices
       pluginName = piSitemap
       controller = Sitemap
       switchableControllerActions {
               Sitemap {
                       1 = index
                       2 = overview
               }
       }
       action = overview
       persistence =< plugin.tx_googleservices.persistence
       persistence {
               storagePid = {$pids.home}
       }
       view =< plugin.tx_googleservices.view
       settings =< plugin.tx_googleservices.settings
       settings {
               startpoint = {$pids.home}
       }
}

sitemap = PAGE
sitemap {
	config {
		xhtml_cleaning = 0
		disableAllHeaderCode = 1
		no_cache = 0
		additionalHeaders {
			10 {
				header = Content-Type:text/xml
			}
		}
	}
	typeNum = 200
	10 < lib.googleservice_sitemap
	10 {
		settings {
			provider = FRUIT\GoogleServices\Service\SitemapProvider\Pages
			depth = 25
		}
   }
}
[end]
```

Could you precise me the goal of the render modification so I could propose a generic fix ?

thank you in advance

**Comment by lochmueller** [comment]
If we still want to use the regular content element, we have to build a clean page template. This is the solution of ETX:news:
https://github.com/georgringer/news/blob/0d34b0e4350fb3eabe261759b4cee56610d9d0d6/Documentation/AdministratorManual/BestPractice/Rss/Index.rst#rss-feeds-by-using-a-normal-plugin

I will check this in the next days/weeks and add same documentation for EXT:Google_services

**Comment by josefglatz** [comment]
I can confirm the php fatal error in a TYPO3 8.7 instance

**Comment by lochmueller** [comment]
There will be no futher actions in this case, because the "seo" extension in TYPO3 9.x is much smarter. I suggest to migrate to EXT:seo.
