### ISSUE TITLE
file link tracking would be nice

### ISSUE THREAD

**Issue by keyrider** [lochmueller/google_services#20]
Hey@all,

great extension and easy to use. Would be nice to have an option for filelink tracking implemented. Dirty workarounds like creating trackable subpages with links to files are not as handy as directly tracking filelinks.

Basically this should be possible:
> Download link tracking
> Clicks on links to downloadable files (e.g. PDF, AVI, WMV) can be tracked as Events or virtual pageviews. When you set up an Event to track clicks on a link, Analytics counts the clicks as event hits. When you set up a virtual pageview to track clicks on a link, Analytics counts the clicks as page hits.
> 
> To track clicks as Events:
> 
> If you use Google Tag Manager to manage your Analytics Tracking, read Analytics Events.
> If you have Analytics tracking added directly to your site, read Event Tracking - Web Tracking on Analytics Developers.
> To track clicks as pageviews:
> 
> If you use Google Tag Manager to manage your Analytics Tracking, read about the Analytics tag.
> If you have Analytics tracking added directly to your site, read Page Tracking - Web Tracking on Analytics Developers.

Source: https://support.google.com/analytics/answer/1012044?hl=en&visit_id=1-636239650271095099-3490656893&rd=1#Download 

Thanks in advance for reading and hopefully mentioning within one of the next versions!

**Comment by lochmueller** [comment]
Good Idea... but no feedback/pull request since now. I will close this issue... if this is still a requirment please contribute with some code fore example...

Regards,
Tim
