### ISSUE TITLE
Integrate the HR date of tt_news

### ISSUE THREAD

**Issue by pixelbreit** [lochmueller/google_services#22]
Hello, is there a way to integrate the HR date of tt_news into the links in the loc tag? 
I use tt_news with realurl and get the links like this:
`<loc>http://www.mydomain.com/news/article/date////example-newstitle.html</loc>` 
But it should look like this: 
`<loc>http://www.mydomain.com/news/article/date/2017/04/19/example-newstitle.html</loc>`

**Comment by lochmueller** [comment]
Hmm.... the link configuration is based on some TS of tt_news: pageTypoLink
I will drop the support for the old tt_news extension. If you have a implementation, feel free to send me a pull request. I will merge it.
Otherwise I suggest to migrate to the new News extsion.

Regards,
Tim
