### ISSUE TITLE
image sitemap in TYPO3 8.7.10 not working

### ISSUE THREAD

**Issue by matthias77** [lochmueller/google_services#24]
Hi, 

 I get this error:

Oops, an error occurred!
Class 'FRUIT\GoogleServices\Domain\Model\Node\Image' not found

Any ideas how to fix it? Many thanks, Matthias

**Comment by lochmueller** [comment]
Thanks for reporting. There was a wrong class name in the FalImages.php provider. Fixed with the attached patch...

**Comment by matthias77** [comment]
Works. Thank you!!
