### ISSUE TITLE
Version 2.0.1 in composer.json in tag 2.0.2

### ISSUE THREAD

**Issue by c0deltin** [lochmueller/google_services#26]
The version in the composer.json in tag 2.0.2 is 2.0.1: 
https://github.com/lochmueller/google_services/blob/eb96df27df681a408faf236bd40f568ed87eb09e/composer.json#L5

**Comment by lochmueller** [comment]
Thanks for the hint. There should be no version in the composer.json at all. I will remove the version in the composer.json. Will be part of the next release...
